Include cstdlib. (#1218)
nanobind uses std::abs, which is either defined in cstdlib or cmath. We
must include one or the other.

Fixes a build failure in our build environment:

```
In file included from third_party/benchmark/bindings/python/google_benchmark/benchmark.cc:6:
./third_party/nanobind/include/nanobind/operators.h:135:45: error: no member named 'abs' in namespace 'std'; did you mean simply 'abs'?
  135 | NB_UNARY_OPERATOR(abs,        abs,          std::abs(l))
      |                                             ^    ~~~
.../llvm_unstable/src/libcxx/include/math.h:456:20: note: 'abs' declared here
  456 | using std::__math::abs;
      |
```